# Initially generated by Buildr 1.4.4

# I use this to generate the jar: buildr clean package
# ... and also to set up Eclipse: buildr eclipse

# Version number for this release
VERSION_NUMBER = "0.0.1"
# Group identifier for projects
GROUP = "info.familyhistories.alliancep2p"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

desc "AllianceP2P Plugin for Friend Subscriptions"
define "friendSubscriptionsPlugin" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  # This is for that Alliance.config file that needs to be at the base of the jar.
  resources.from _('src/main/resources-jar')

  ALLIANCEP2P = 'alliancep2p:alliance:jar:1.0.182'
  compile.with ALLIANCEP2P # Add classpath dependencies
  package(:jar)
end
